"""remove_subtitle_tags_add_book_type

Revision ID: 03e3f0f4bf08
Revises: 460ba3717267
Create Date: 2026-02-26 17:24:40.198338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e3f0f4bf08'
down_revision: Union[str, Sequence[str], None] = '460ba3717267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_type', sa.String(length=32), nullable=False, comment='书籍类型：physical / ebook / physical,ebook'))
        batch_op.add_column(sa.Column('physical_location', sa.String(length=256), nullable=True, comment='纸质书存放位置'))
        batch_op.drop_column('has_physical')
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.VARCHAR(length=512), nullable=True))
        batch_op.add_column(sa.Column('has_physical', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('physical_location')
        batch_op.drop_column('book_type')

    # ### end Alembic commands ###
