"""add read_status and init

Revision ID: 3dac6bf06376
Revises: 295135a83a0c
Create Date: 2026-03-01 21:26:01.554392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dac6bf06376'
down_revision: Union[str, Sequence[str], None] = '295135a83a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_status', sa.String(length=16), server_default='未读', nullable=False, comment='阅读状态：已读, 在读, 未读, 选读, 翻阅, 搁置'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('read_status')

    # ### end Alembic commands ###
