"""Remove page_count from books

Revision ID: 4066fa43bab7
Revises: 3dac6bf06376
Create Date: 2026-03-02 20:47:02.284626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4066fa43bab7'
down_revision: Union[str, Sequence[str], None] = '3dac6bf06376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('page_count')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_count', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
