"""add scrape_tasks table

Revision ID: 6e57b93f0684
Revises: d22ade0371b7
Create Date: 2026-03-10 15:29:54.092042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e57b93f0684'
down_revision: Union[str, Sequence[str], None] = 'd22ade0371b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False, comment='客户端唯一任务标识 (UUID hex)'),
    sa.Column('query', sa.String(length=512), nullable=False, comment='刮削查询 (ISBN 或书名)'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='processing / completed / failed'),
    sa.Column('result_json', sa.Text(), nullable=True, comment='JSON 序列化的刮削结果'),
    sa.Column('error', sa.Text(), nullable=True, comment='失败时的错误信息'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='提交任务的用户 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_tasks_task_id'), ['task_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_tasks_task_id'))

    op.drop_table('scrape_tasks')
    # ### end Alembic commands ###
